name: 🔄 Update APOD in README

on:
  schedule:
    - cron: '0 8 * * *' # Every day at 8 AM UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone repo
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm install node-fetch

      - name: 🚀 Run update script
        run: node updateReadme.js

      - name: 📤 Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add NASA_api_documentation.md
          git commit -m "🔄 Update APOD from NASA API"
          git push